[book]
authors = ["yxj"]
language = "zh-cn"
multilingual = false
src = "src"
title = "Site by yxj"

[output.html]
git-repository-url = "https://yang-xijie.github.io/"
git-repository-icon = "fa-github"
