[book]
authors = ["yxj"]
language = "zh-cn"
multilingual = false
src = "src"
title = "yxj's Site"

[output.html]
git-repository-url = "https://github.com/Yang-Xijie/yang-xijie.github.io"
git-repository-icon = "fa-github"
