[book]
title = "yxj"
authors = ["yxj"]
description = "Yang-Xijie's own site"
src = "src"
language = "zh-cn"
multilingual = false

[output.html]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
no-section-label = true
git-repository-url = "https://github.com/Yang-Xijie/yang-xijie.github.io"
git-repository-icon = "fa-github"

[output.html.print]
enable = false

[output.html.search]
enable = false