# [Info]
site_name: 杨希杰的个人网站 # 左上角标题
site_url: https://yang-xijie.github.io
site_author: 杨希杰
site_description: 杨希杰的个人网站

# [UI]
## [top]
theme:
  name: material
  palette: 
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/Yang-Xijie/yang-xijie.github.io # 右上角点击跳转的链接
repo_name: yang-xijie.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2022 杨希杰 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/24502827
      name: Bilibili | 我不是小杰 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Yang-Xijie
      name: GitHub | Yang-Xijie

# [Navigtion]
nav:
  - 讲稿: 
    - LECTURE/index.md 
    - Linux: LECTURE/Linux/linux.md
    - Markdown: LECTURE/Markdown/markdown.md
    - Git: 
      - Git: LECTURE/Git/git.md
      - Git demos: LECTURE/Git/git-demos.md
      - Git teamwork: LECTURE/Git/git-teamwork.md
    - 应用开发设计: LECTURE/App/app-design.md
    - 在macOS上用VSCode写C++代码: 
      - 0 介绍: LECTURE/vscode-cpp/0_about.md
      - 1 前言和课程说明: LECTURE/vscode-cpp/1_前言和课程说明.md
      - 2 认识macOS的文件系统: LECTURE/vscode-cpp/2_认识macOS的文件系统.md
      - 3 认识程序: LECTURE/vscode-cpp/3_认识程序.md
      - 4 认识终端和shell: LECTURE/vscode-cpp/4_认识终端和shell.md
      - 5 开启VSCode的大门: LECTURE/vscode-cpp/5_开启VSCode的大门.md
      - 6 VSCode代码运行自动化: LECTURE/vscode-cpp/6_VSCode代码运行自动化.md
      - 7 用VSCode调试Cpp代码: LECTURE/vscode-cpp/7_用VSCode调试Cpp代码.md
      - 8 课程回顾: LECTURE/vscode-cpp/8_课程回顾.md
      - 其他: LECTURE/vscode-cpp/9_others.md
      - 极速版: LECTURE/vscode-cpp/10_极速版.md
      - 补充: LECTURE/vscode-cpp/11_补充.md
    - 在macOS上用VSCode写Python: LECTURE/vscode-python/vscode-python.md
    - 英语音标教学: LECTURE/English/phonetic-symbol.md
  - 博客:
    - BLOG/index.md
    - CG:
      - Computer Graphics: BLOG/ComputerGraphics/cg-notes.md
      - GAMES101: BLOG/ComputerGraphics/games101.md
      - Blender: BLOG/ComputerGraphics/blender-notes.md
      - Unity: BLOG/ComputerGraphics/unity-notes.md
      - UE: BLOG/ComputerGraphics/ue-notes.md
    - 日语:
      - 笔记2/3: BLOG/Japanese/notes-2202-2203.md
      - 笔记4: BLOG/Japanese/notes-2204.md
      - 笔记5: BLOG/Japanese/notes-2205.md
      - 动词整理: BLOG/Japanese/verb.md
      - 形容词整理: BLOG/Japanese/adj.md
      - 名词整理: BLOG/Japanese/noun.md
      - 语法整理: BLOG/Japanese/grammar.md
      - 作文: BLOG/Japanese/essays.md
      - たんたんめん推特: BLOG/Japanese/tantanmen-translation.md
    - OS:
      - TODO ExOS设计: BLOG/OS/os-design.md
      - fork/exec/spawn: BLOG/OS/fork-exec-spawn.md
      - fork例: BLOG/OS/fork-example.md
    - Linux:
      - vim: BLOG/Linux/vim.md
      - tmux: BLOG/Linux/tmux.md
      - UNIX: BLOG/Linux/unix.md
      - 内核编译: BLOG/Linux/kernel-compile.md
    - macOS:
      - 使用tree命令和访达进行任务管理: BLOG/macOS/tree.md
      - 辅助功能缩放: BLOG/macOS/zoom.md
      - Mac与Android的文件传输: BLOG/macOS/sharing-mac-android.md
      - MAD制作流程: BLOG/macOS/mad.md
      - OBS开直播: BLOG/macOS/stream.md
    - UOS:
      - 相关链接: BLOG/UOS/links.md
    - GitHub:
      - 镜像到Gitee: BLOG/GitHub/mirror.md
    - Markdown:
      - Markdown语法初学习: BLOG/Markdown/grammars.md
      - TODO ExMark规范: BLOG/Markdown/ExMark-spec-zh.txt
      - MkDocs静态网站构建: BLOG/Markdown/mdbook-site.md
      - mdBook静态网站构建: BLOG/Markdown/mkdocs-site.md
      - GitHub Pages简介: BLOG/Markdown/github-pages.md
    - 基础:
      - 数学:
        - Latex简易符号: BLOG/Foundation/Math/latex.md
        - 线性代数笔记: BLOG/Foundation/Math/linear.md
        - 常用泰勒级数: BLOG/Foundation/Math/taylor.md
        - 最大似然估计: BLOG/Foundation/Math/max-pr.md
        - BLOG/Foundation/Math/sympy-det.md
      - 物理:
        - Gauss公式和Stokes公式: BLOG/Foundation/Physics/guass-stokes.md
        - 电磁学期末复习: BLOG/Foundation/Physics/electromagnetics.md
      - 电子:
        - 各种存储器间的关系: BLOG/Foundation/EE/storage.md
        - 二阶线性时不变电路: BLOG/Foundation/EE/rlc.md
      - 网络:
        - 知识点总结: BLOG/Network/learning.md
        - 专有名词速查: BLOG/Network/nouns.md
        - GraphQL Hasura: BLOG/Network/graphql.md
      - 机器学习:
        - 动手学深度学习笔记: BLOG/Deeplearning/d2l.md
        - 语音识别笔记: BLOG/Deeplearning/speech-recognition.md
        - 数据加载优化: BLOG/Deeplearning/parallel-load.md
        - DDP: 
          - DDP调研: BLOG/Deeplearning/ddp.md
          - ddp-note.py: BLOG/Deeplearning/ddp-note.md
    - 其他:
      - 视频信息初探: BLOG/Others/video-info.md
  - 开发:
    - DEV/index.md
    - Xcode:
      - 新建开发模块: DEV/Xcode/scheme-dev.md
      - Markup Syntax: DEV/Xcode/markup.md
      - 新建文件注释: DEV/Xcode/file-header.md
      - 常用快捷键: DEV/Xcode/shortcuts.md
      - Set Build Number: DEV/Xcode/set-build-number.md
      - Crash Analysis: DEV/Xcode/crash-analysis.md
    - SwiftUI:
      - Data Essentials: DEV/SwiftUI/data-essentials.md
    - AppKit:
      - 纯代码创建项目: DEV/AppKit/programmatically.md
      - 苹果平台应用开发之路: DEV/AppKit/road.md
    - ExNotes:
      - ExNotes设计文档: DEV/ExNotes/design.md
      - ExNotes开发考量: DEV/ExNotes/learning.md
    - 编程:
      - 推荐的学习路线: DEV/Programming/recommendation.md
      - C:
        - 笔记整理: DEV/Programming/C/review.md
        - 常用函数: DEV/Programming/C/final.md
        - stdout按行刷新: DEV/Programming/C/stdout-fflush.md
        - 二维数组调试: DEV/Programming/C/watch-matrix.md
      - Swift:
        - 并行计算: DEV/Programming/Swift/parallel.md
        - Swift教学作业: DEV/Programming/Swift/hw.md
        - TODO Language Guide: DEV/Programming/Swift/guide.md
      - Python:
        - 不喜欢Python的理由: DEV/Programming/Python/dislike.md
        - 复制拷贝: DEV/Programming/Python/copy.md
        - numpy速查表: DEV/Programming/Python/numpy-overview.md
      - C#:
        - 学习笔记: DEV/Programming/Csharp/learning.md
      - C++:
        - 1 C++的几个基本问题: DEV/Programming/Cpp/1.md
        - 2 函数重载: DEV/Programming/Cpp/2.md
        - 3 类: DEV/Programming/Cpp/3.md
        - 4 操作符重载: DEV/Programming/Cpp/4.md
        - 5 类的继承与派生: DEV/Programming/Cpp/5.md
        - 6 模版: DEV/Programming/Cpp/6.md
        - 7 异常处理: DEV/Programming/Cpp/7.md
        - 8 流类库的输入与输出: DEV/Programming/Cpp/8.md
        - List: DEV/Programming/Cpp/list.md
        - Stack: DEV/Programming/Cpp/stack.md
        - 类数据成员: DEV/Programming/Cpp/class-properties.md
        - Google风格: DEV/Programming/Cpp/google-format.md
        - 考试复习: DEV/Programming/Cpp/final.md
        - OJ技巧和策略: DEV/Programming/Cpp/oj.md
      - MATLAB:
        - MATLAB入门: DEV/Programming/MATLAB/tour.md
        - 抛硬币的涨落问题: DEV/Programming/MATLAB/coin.md
        - 命令行MATLAB: DEV/Programming/MATLAB/terminal-matlab.md
  - 二次元:
    - 2/index.md
    - 番:
      - 番剧评价: 2/Anime/anime-rating.md
      - 神作: 2/Anime/anime-rating-extraordinary.md
      - 上乘: 2/Anime/anime-rating-great.md
      - 好: 2/Anime/anime-rating-good.md
    - 原神:
      - 计划: 2/Genshin/plan.md
      - 暴击爆伤配比: 2/Genshin/crit-calculation.md
    - 喜欢的:
      - 插画: 2/Sukina/pictures.md
      - 二次元女生: 2/Sukina/kawaii.md
      - 画师: 2/Sukina/artists.md
      - vtuber: 2/Sukina/vtuber.md
      - 音声: 2/Sukina/voice.md
  - 三次元:
    - 3/index.md
    - 随笔记:
      - 3/Jottings/15.md
      - 3/Jottings/14.md
      - 3/Jottings/13.md
      - 3/Jottings/12.md
      - 3/Jottings/11.md
      - 3/Jottings/10.md
      - 3/Jottings/9.md
      - 3/Jottings/8.md
      - 3/Jottings/7.md
      - 3/Jottings/6.md
      - 3/Jottings/5.md
      - 3/Jottings/4.md
      - 3/Jottings/3.md
      - 3/Jottings/2.md
      - 3/Jottings/1.md
      - 3/Jottings/0.md
      - 3/Jottings/2018-1.md
      - 3/Jottings/2018-2.md
      - 3/Jottings/2017.md
      - 3/Jottings/2016.md
    - 文章:
      - TODO 课程: 3/Articles/cirriculum.md
      - 3/Articles/220520-what-is-game.md
      - 3/Articles/220506-stop-jianshu.md
      - 3/Articles/220505-library-thu.md
      - 3/Articles/220415-interestx2.md
      - 3/Articles/220410-job-discussion.md
      - 3/Articles/220410-independence.md
      - 3/Articles/220408-appreciating-girl.md
      - 3/Articles/220402-languages-comparision.md
      - 3/Articles/220324-thoughts-996.md
      - 3/Articles/220107-want-to-be.md
      - 3/Articles/211104-emotion-bad.md
      - 3/Articles/210928-apple-online-job-meeting.md
      - 3/Articles/2109-covid-influence.md
      - 3/Articles/2109-group-clear.md
      - 3/Articles/210820-cccc-event.md
      - 3/Articles/210801-affection-3.md
      - 3/Articles/210519-app-dev-experience.md
      - 3/Articles/210516-apple-education-address.md
      - 3/Articles/210502-extend-your-way.md
      - 3/Articles/201119-a-new-review.md
      - 3/Articles/200607-gaokao-memory.md
      - 3/Articles/200713-sutuo-and-me.md
      - 3/Articles/200703-talk-with-junior.md
      - 3/Articles/200604-small-goal.md
      - 3/Articles/200602-tennkinoko.md
      - 3/Articles/200506-why.md
      - 3/Articles/2005-travel.md
      - 3/Articles/190730-tangyan-rd-23.md
      - 3/Articles/190723-feelings-in-6-days.md
      - 3/Articles/190707-address-to-nonlocal-students.md
      - 3/Articles/190629-affection-2.md
      - 3/Articles/1905-non-intelligent.md
      - 3/Articles/1901-go-to-thu.md
      - 3/Articles/1811-do-it.md
      - 3/Articles/1808-ideality-and-reality.md
      - 3/Articles/1806-apply-thu.md
      - 3/Articles/18-tree.md
      - 3/Articles/18-what-i-love.md
      - 3/Articles/17-dream-2017.md
      - 3/Articles/14-affection-1.md
    - 文学:
      - 3/Literature/proses.md
      - 3/Literature/poems.md
    - 日记:
      - 3/Diary2022/2205.md
      - 3/Diary2022/2204.md
      - 3/Diary2022/2203.md
      - 3/Diary2022/2202.md
      - 3/Diary2022/2201.md
      - 3/Diary2021/2112.md
      - 3/Diary2021/2111.md
      - 3/Diary2021/2110.md
      - 3/Diary2021/2109.md
      - 3/Diary2021/2108.md
      - 3/Diary2021/2107.md
      - 3/Diary2021/2106.md
      - 3/Diary2021/2105.md
      - 3/Diary2021/2104.md
      - 3/Diary2021/2103.md
      - 3/Diary2021/2102.md
      - 3/Diary2021/2101.md
      - 3/Diary2020/2012.md
      - 3/Diary2020/2011.md
      - 3/Diary2020/2010.md
      - 3/Diary2020/2009.md
      - 3/Diary2020/2008.md
      - 3/Diary2020/2007.md
      - 3/Diary2020/2006.md
      - 3/Diary2020/2005.md
      - 3/Diary2020/2004.md
      - 3/Diary2020/2003.md
      - 3/Diary2020/200312-start.md
      - 3/Diary2020/2001.md
      - 3/Diary2019/191123.md
      - 3/Diary2019/1909-12.md
      - 3/Diary2019/190714.md
      - 3/Diary2019/1901-winter-thu.md
      - 3/Diary2018/1812.md
      - 3/Diary2018/1811.md
      - 3/Diary2018/1810.md
      - 3/Diary2018/1809.md
      - 3/Diary2018/1808.md
      - 3/Diary2018/1807.md
      - 3/Diary2018/1805-06.md
      - 3/Diary2018/1803-04.md
      - 3/Diary2018/1801-02.md
      - 3/Diary2017/1710-12.md
      - 3/Diary2017/1707-09.md
      - 3/Diary2017/1704-06.md
      - 3/Diary2017/1701-03.md
      - 3/Diary2016/16.md
    - 个人信息:
      - 3/Info/accounts.md
      - 3/Info/diary-index.md
  - 转载:
    - REPRODUCE/index.md
    - 提问的智慧: REPRODUCE/how-to-ask-questions-the-smart-way.md
    - Tim Cook在Duke大学的演讲: REPRODUCE/tim-cook-at-duke.md
  - 关于:
    - ABOUT/index.md # 使用两个index 这样子左上角第一次打开会是所有Tab 而不是ABOUT
    - 个人履历: ABOUT/cv-full.md
    - 支持作者: ABOUT/support.md
    - 文章编写帮助: ABOUT/help.md
    - 网站构建: ABOUT/build.md
    - 测试文档: ABOUT/test.md

# [Extensions]
plugins:
  - search # 现在还不支持中文搜索 支持之后可以设置语言
  - tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
extra_javascript:
  - mkdocs/javascripts/mathjax.js # latex支持
  - https://polyfill.io/v3/polyfill.min.js?features=es6 # latex支持
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # latex支持
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
