# [Info]
site_name: 杨希杰的个人网站 # 左上角标题
site_url: https://yang-xijie.github.io
site_author: 杨希杰
site_description: 杨希杰的个人网站

# [UI]
## [top]
theme:
  name: material
  palette: 
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/Yang-Xijie/yang-xijie.github.io # 右上角点击跳转的链接
repo_name: yang-xijie.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2022 杨希杰 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/24502827
      name: Bilibili | 我不是小杰 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Yang-Xijie
      name: GitHub | Yang-Xijie

# [Navigtion]
nav:
  - 讲稿: 
    - LECTURE/index.md 
    - Linux: LECTURE/linux/linux.md
    - Markdown: LECTURE/markdown/markdown.md
    - Git: 
      - Git: LECTURE/git/git.md
      - Git demos: LECTURE/git/git-demos.md
      - Git teamwork: LECTURE/git/git-teamwork.md
    - 在macOS上用VSCode写C++代码: 
      - 0 介绍: LECTURE/vscode-cpp/0_about.md
      - 1 前言和课程说明: LECTURE/vscode-cpp/1_前言和课程说明.md
      - 2 认识macOS的文件系统: LECTURE/vscode-cpp/2_认识macOS的文件系统.md
      - 3 认识程序: LECTURE/vscode-cpp/3_认识程序.md
      - 4 认识终端和shell: LECTURE/vscode-cpp/4_认识终端和shell.md
      - 5 开启VSCode的大门: LECTURE/vscode-cpp/5_开启VSCode的大门.md
      - 6 VSCode代码运行自动化: LECTURE/vscode-cpp/6_VSCode代码运行自动化.md
      - 7 用VSCode调试Cpp代码: LECTURE/vscode-cpp/7_用VSCode调试Cpp代码.md
      - 8 课程回顾: LECTURE/vscode-cpp/8_课程回顾.md
      - 其他: LECTURE/vscode-cpp/9_others.md
      - 极速版: LECTURE/vscode-cpp/10_极速版.md
      - 补充: LECTURE/vscode-cpp/11_补充.md
    - 在macOS上用VSCode写Python: LECTURE/vscode-python/vscode-python.md
    - 英语音标教学: LECTURE/english/phonetic-symbol.md
  - 博客:
    - BLOG/index.md
    - OS:
      - TODO rCore笔记: BLOG/OS/rcore-learning.md
      - TODO yxj OS设计: BLOG/OS/os-design.md
    - 机器学习:
      - TODO 动手学深度学习笔记: BLOG/deeplearning/动手学深度学习.md
    - 日语:
      - TODO 语法笔记: BLOG/japanese/notes.md
      - TODO 动词整理: BLOG/japanese/verb-note.md
      - 形容词整理: BLOG/japanese/adj-note.md
      - 名词整理: BLOG/japanese/noun-note.md
    - macOS:
      - 使用tree命令和访达进行任务管理: BLOG/macOS/tree.md
      - 辅助功能缩放: BLOG/macOS/zoom.md
      - Mac与Android的文件传输: BLOG/macOS/sharing-mac-android.md
      - MAD制作流程: BLOG/macOS/mad.md
      - OBS开直播: BLOG/macOS/stream.md
    - Linux:
      - vim: BLOG/Linux/vim.md
      - tmux: BLOG/Linux/tmux.md
      - Unix: BLOG/Linux/unix.md
    - 编程:
      - Swift:
        - 并行计算: BLOG/swift/parallel.md
        - Swift教学作业: BLOG/swift/hw.md
        - TODO Language Guide: BLOG/swift/guide.md
      - C:
        - C常用函数: BLOG/C/final.md
        - C语言知识点: BLOG/C/review.md
      - C++:
        - 1 C++的几个基本问题: BLOG/Cpp/1.md
        - 2 函数重载: BLOG/Cpp/2.md
        - 3 类: BLOG/Cpp/3.md
        - 4 操作符重载: BLOG/Cpp/4.md
        - 5 类的继承与派生: BLOG/Cpp/5.md
        - 6 模版: BLOG/Cpp/6.md
        - 7 异常处理: BLOG/Cpp/7.md
        - 8 流类库的输入与输出: BLOG/Cpp/8.md
        - List: BLOG/Cpp/List.md
        - Stack: BLOG/Cpp/Stack.md
        - 类数据成员: BLOG/Cpp/class-properties.md
        - Google风格: BLOG/Cpp/google-format.md
      - MATLAB:
        - MATLAB入门: BLOG/MATLAB/tour.md
        - 抛硬币的涨落问题: BLOG/MATLAB/coin.md
        - 命令行MATLAB: BLOG/MATLAB/terminal-matlab.md
      - Python:
        - TODO 不喜欢Python的理由: BLOG/Python/dislike.md
        - 复制拷贝: BLOG/Python/copy.md
        - numpy速查表: BLOG/Python/numpy-overview.md
    - 基础:
      - 数学:
        - Latex简易符号: BLOG/math/latex.md
        - 线性代数笔记: BLOG/math/linear.md
        - 常用泰勒级数: BLOG/math/taylor.md
        - 最大似然估计: BLOG/math/max-pr.md
      - 物理:
        - Gauss公式和Stokes公式: BLOG/physics/guass-stokes.md
        - 电磁学期末复习: BLOG/physics/electromagnetics.md
      - 电子:
        - 各种存储器间的关系: BLOG/EE/storage.md
        - 二阶线性时不变电路: BLOG/EE/rlc.md
    - Markdown:
      - Markdown语法初学习: BLOG/markdown/grammars.md
      - TODO ExMark规范: BLOG/markdown/ExMark-spec-zh.txt
    - 其他:
      - 视频信息初探: BLOG/video/info.md
      - GraphQL Hasura: BLOG/network/graphql.md
  - 开发:
    - DEV/index.md
    - Xcode:
      - 新建开发模块: DEV/Xcode/scheme-dev.md
      - Set Build Number: DEV/Xcode/set-build-number.md
      - Markup Syntax: DEV/Xcode/markup.md
      - 新建文件注释: DEV/Xcode/file-header.md
      - 常用快捷键: DEV/Xcode/shortcuts.md
    - ExNotes:
      - ExNotes设计文档: DEV/ExNotes/exnotes-doc.md
      - ExNotes开发考量: DEV/ExNotes/learning.md
    - SwiftUI:
      - Data Essentials: DEV/SwiftUI/data-essentials.md
    - AppKit:
      - 纯代码创建项目: DEV/AppKit/programmatically.md
  - 二次元:
    - 2/index.md
    - 番:
      - 番剧评价: 2/ANIME/anime-rating.md
      - 神作: 2/ANIME/anime-rating-extraordinary.md
      - 上乘: 2/ANIME/anime-rating-great.md
      - 好: 2/ANIME/anime-rating-good.md
      - 制作公司: 2/ANIME/anime-production.md
    - 可爱的二次元女生: 2/kawaii.md
    - 喜欢的画师: 2/artists.md
    - 喜欢的画: 2/pictures.md
    - 喜欢的音声: 2/voice.md
    - 喜欢的vtuber: 2/vtuber.md
    - 原神:
      - 计划: 2/genshin/plan.md
  - 三次元:
    - 3/index.md
    - 个人账号: 3/accounts.md
    - 日记说明与索引: 3/diary-index.md
  - 关于: 
    - ABOUT/index.md # 使用两个index 这样子左上角第一次打开会是所有Tab 而不是ABOUT
    - 网站构建: ABOUT/build.md
    - 支持: ABOUT/support.md
    - 测试: ABOUT/test.md

# [Extensions]
plugins:
  - search # 现在还不支持中文搜索 支持之后可以设置语言
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
extra_javascript:
  - mkdocs/javascripts/mathjax.js # latex支持
  - https://polyfill.io/v3/polyfill.min.js?features=es6 # latex支持
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # latex支持
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
